numberOfTasks = ("12")
hours_spent = ("1.5")
CourseName = ("Python")
timeForOneTask = (float(hours_spent) / float(numberOfTasks))
print("Курс:",CourseName,", всего задач:",numberOfTasks,", затраченно часов:",hours_spent,"часа", ",среднее время выполнения:",timeForOneTask,"часа.")